### PR TITLE
Refactor and HUD

### PR DESCRIPTION
**Pull request by schwal10**
A few, big changes in this PR
-Added spare parts powerup
-Split up fringe file into different files
-Added HUD and player systems
-Adjusted some acceleration logic to reduce orbiting issues

### CODE REVIEW

**Comment by jackinloadup** [comment]
sweet! I'll review and merge.

**Comment by pavellishin** [comment]
I remember seeing some comments about CORS issues; if you don't want to deal with the rigmarole of setting up VSCode and extensions, you can run `python3 -m http.server` in that folder, and navigate to http://localhost:8000 if you're on OS X: https://osxdaily.com/2018/06/13/how-install-update-python-3x-mac/

Presumably something similar works in windows.

**Comment by pavellishin** [comment]
It's also incredibly laggy to the point of unplayability in Firefox for me :( And there are a ton more enemies swarming me than I recall!

but my god this brings back memories in Chrome!

**Comment by schwal10** [comment]
@pavellishin 
Good call, I didn't even think about Python. I can add that to the README!

That is good to know about Firefox, I have not really been testing this out on other browsers so that's my bad. I'll make a note/issue to look into that as well as possibly making some general optimizations in the code.

- [ ] Add python server info to the REAME

**Comment by jackinloadup** [comment]
@schwal10 Awesome work!! You rock.

**Pull request merged**
